Ansible libvirt
===============

A stash of Ansible roles that allow you to control libvirt virtual machines

Requirements
------------

* Ansible
* Host capable of running libvirt

Content Roles
-------------

* host/provision - install everything required on the host
* images/ubuntu-cloud - download and prepare a Ubuntu cloud images (default: Trusty 14.04)
* network/bridge - configure a libvirt network for nat bridge mode
* domain/create - create and start a new virtual machine
* domain/list - list virtual machines
* domain/kill - stop and undefine a virtual machine
* domain/port_forward - forward certain network ports from the host to a domain
* facts/new - create facts for a new virtual machine
* facts/store - save facts to a virtual machine
* facts/delete - remove facts about a virtual machine

License
-------

The MIT License (MIT)

Copyright (c) 2015 HicknHack Software GmbH

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
