---
- name: Autostart | List domains
  ansible.builtin.command: virsh list --autostart --name
  changed_when: false
  register: libvirt_list_autostart_result

- name: Autostart | Enable
  ansible.builtin.command: "virsh autostart {{ libvirt_result_domain_name }}"
  changed_when: true
  when: libvirt_autostart and (libvirt_result_domain_name not in libvirt_list_autostart_result.stdout_lines)

- name: Autostart | Disable
  ansible.builtin.command: "virsh autostart {{ libvirt_result_domain_name }} --disable"
  changed_when: true
  when: not libvirt_autostart and (libvirt_result_domain_name in libvirt_list_autostart_result.stdout_lines)
