---
- name: Base Image | Copy
  ansible.builtin.command: >
    cp
    {{ libvirt_base_image }}
    {{ libvirt_result_domain_name }}.img
  args:
    chdir: "{{ libvirt_images_path }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.img"
  register: libvirt_copy_image_result
  when: libvirt_base_image_mode == 'copy'

- name: Base Image | Snapshot
  ansible.builtin.command: >
    qemu-img create
    -f qcow2
    -b {{ libvirt_base_image }}
    -F qcow2
    {{ libvirt_result_domain_name }}.img
  args:
    chdir: "{{ libvirt_images_path }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.img"
  register: libvirt_snapshot_image_result
  when: libvirt_base_image_mode == 'snapshot'

- name: Base Image | Resize
  ansible.builtin.command: >
    qemu-img resize
    {{ libvirt_result_domain_name }}.img
    {{ libvirt_vm_disk_size }}
  args:
    chdir: "{{ libvirt_images_path }}"
  changed_when: true
  when: (libvirt_vm_disk_size is defined)
    and (libvirt_copy_image_result.changed or libvirt_snapshot_image_result.changed)
