---
- name: ConfigDrive | directories
  ansible.builtin.file:
    path: '{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive/{{ item.key | dirname }}'
    state: directory
  loop: '{{ libvirt_configdrive_files | dict2items }}'

- name: ConfigDrive | content
  ansible.builtin.copy:
    dest: '{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive/{{ item.key }}'
    content: '{{ item.value }}'
  loop: '{{ libvirt_configdrive_files | dict2items }}'
  register: libvirt_configdrive_result

- name: ConfigDrive | iso image
  ansible.builtin.command: >
    genisoimage -joliet -rock -volid config-2
    -o {{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive.iso
    -r {{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive
  when: libvirt_configdrive_result.changed
