---
- name: Create Domain | Template
  ansible.builtin.template:
    dest: "/tmp/{{ libvirt_result_domain_name }}.xml"
    src: "machine.xml.j2"
    mode: "644"

- name: Create Domain | Define
  ansible.builtin.command: "virsh define /tmp/{{ libvirt_result_domain_name }}.xml"
  changed_when: true

- name: Create Domain | Start
  ansible.builtin.command: "virsh start {{ libvirt_result_domain_name }}"
  changed_when: true
  notify:
    - Wait for remote ports
    - Check ssh login
    - Check for dns entry
