---
- name: Create lvm disk
  ansible.builtin.fail:
    msg: 'LVM disk creation is not implemented yet!'
  when: (disk.type | default('image', true)) == 'lvm'

- name: Create image disk
  ansible.builtin.command: >
    qemu-img create
    -f {{ disk.image_type | default('qcow2', true) }}
    extra_{{ disk.id | default('data', true) }}.img
    {{ disk.size }}
  args:
    chdir: "{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}/extra_{{ disk.id | default('data', true) }}.img"
  when: (disk.type | default('image', true)) == 'image'
