---
- name: list | all domains
  ansible.builtin.command: virsh list --all --name
  changed_when: no
  register: libvirt_list_all_result
  tags:
  - facts

- name: list | extract
  ansible.builtin.set_fact:
    libvirt_all_domains: "{{ libvirt_list_all_result.stdout_lines }}"
  tags:
  - facts
