---
- name: Mac and Ip | Extract mac address
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      virsh dumpxml {{ libvirt_result_domain_name }}
      | grep 'mac address'
      | cut -f 2 -d "'"
    executable: "/bin/bash"
  changed_when: false
  register: extract_mac_address_result

- name: Mac and Ip | Wait for dhcp ip address
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      until arp -an | grep -q -F {{ extract_mac_address_result.stdout }}; do
        sleep 1
      done
      arp -an | grep -F {{ extract_mac_address_result.stdout }} | cut -f 2 -d "(" | cut -f 1 -d ")"
    executable: "/bin/bash"
  changed_when: false
  register: extract_ip_address_result

- name: Mac and Ip | Extract facts
  ansible.builtin.set_fact:
    libvirt_result_ip_address: "{{ extract_ip_address_result.stdout }}"
    libvirt_result_mac_address: "{{ extract_mac_address_result.stdout }}"
