---
- name: store_facts | facts directory
  ansible.builtin.file:
    path: "{{ ansible_facts_path }}"
    state: directory
    recurse: yes

- name: store_facts | generated ssh_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "ssh_port"
    value: "{{ libvirt_result_ssh_port }}"
  when: libvirt_result_ssh_port_generated | bool

- name: store_facts | generated rdp_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "rdp_port"
    value: "{{ libvirt_result_rdp_port }}"
  when: libvirt_result_rdp_port_generated | bool

- name: store_facts | generated winrm_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "winrm_port"
    value: "{{ libvirt_result_winrm_port }}"
  when: libvirt_result_winrm_port_generated | bool
