---
- name: Store Facts | Facts directory
  ansible.builtin.file:
    path: "{{ ansible_facts_path }}"
    state: directory
    mode: "755"

- name: Store Facts | Generated ssh_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "ssh_port"
    value: "{{ libvirt_result_ssh_port }}"
    mode: "644"
  when: libvirt_result_ssh_port_generated | bool

- name: Store Facts | Generated rdp_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "rdp_port"
    value: "{{ libvirt_result_rdp_port }}"
    mode: "644"
  when: libvirt_result_rdp_port_generated | bool

- name: Store Facts | Generated winrm_port
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "winrm_port"
    value: "{{ libvirt_result_winrm_port }}"
    mode: "644"
  when: libvirt_result_winrm_port_generated | bool
