---

- name: wait for remote ports
  ansible.builtin.wait_for:
    host: "{{ item.ip }}"
    port: >-
      {{ item.winrm_port
          if (item.winrm_port | int) > 0
        else
          item.ssh_port
      }}
    timeout: 360 # seconds
  become: false
  delegate_to: 127.0.0.1
  loop: "{{ libvirt_wait_hosts }}"

# wait_for might not be enough for a successful SSH login, probably due to
# https://stackoverflow.com/questions/30576778/ansible-wait-for-for-connecting-machine-to-actually-login#comment60208811_30576778
- name: check ssh login
  ansible.builtin.command: >
    ssh
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    -p {{ item.ssh_port }} {{ item.ip }}
    -l ansible
    exit
  register: ssh_test
  until: ssh_test.rc == 0
  retries: 12
  delay:  5
  changed_when: false
  when: (item.winrm_port | int) <= 0
  become: false
  delegate_to: 127.0.0.1
  loop: "{{ libvirt_wait_hosts }}"

- name: check for dns entry
  ansible.builtin.command: host {{ item.name }}
  register: host_test
  until: host_test.rc == 0
  retries: 15
  delay: 5
  changed_when: false
  loop: "{{ libvirt_wait_hosts }}"
