---
- name: Wait for remote ports
  delegate_to: 127.0.0.1
  become: false
  ansible.builtin.wait_for:
    host: "{{ item.ip }}"
    port: >-
      {{ item.winrm_port
          if (item.winrm_port | int) > 0
        else
          item.ssh_port
      }}
    timeout: 360 # seconds
  loop: "{{ libvirt_wait_hosts }}"

# wait_for might not be enough for a successful SSH login, probably due to
# https://stackoverflow.com/questions/30576778/ansible-wait-for-for-connecting-machine-to-actually-login#comment60208811_30576778
- name: Check ssh login
  delegate_to: 127.0.0.1
  become: false
  ansible.builtin.command:
    cmd: >
      ssh
      -o StrictHostKeyChecking=accept-new
      -p {{ item.ssh_port }} {{ item.ip }}
      -l {{ libvirt_ssh_login }}
      -- sudo netplan apply
  register: ssh_test
  until: ssh_test.rc == 0
  retries: 12
  delay: 5
  changed_when: false
  when: (item.winrm_port | int) <= 0
  loop: "{{ libvirt_wait_hosts }}"

- name: Check for dns entry
  ansible.builtin.command:
    cmd: host -t A {{ item.name }}
  register: host_test
  until: host_test.rc == 0
  retries: 15
  delay: 5
  changed_when: false
  loop: "{{ libvirt_wait_hosts }}"
