---
- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: libvirt_host_packages

- name: machine hooks folder
  file:
    dest: "{{ libvirt_host_qemu_machine_hooks_folder }}"
    state: directory

- name: qemu hook
  template:
    dest: "{{ libvirt_host_qemu_hook }}"
    src: "qemu_hook.j2"
    mode: 700
  notify:
    - restart libvirt

- name: increase semaphore count
  template:
    dest: "/etc/sysctl.d/local.conf"
    src: "sysctl_local.conf.j2"

- name: disable audit
  lineinfile:
    dest: "/etc/libvirt/libvirtd.conf"
    regexp: "^audit_level"
    line: "audit_level = 0"
  notify:
    - restart libvirt

- name: network hook
  template:
    dest: "{{ network_interface_up_hooks_path }}/libvirt"
    src: "if_up_libvirt.sh.j2"
    mode: 700
