---
- name: Shutdown
  ansible.builtin.include_tasks: shutdown.yml
- name: Undefine
  ansible.builtin.include_tasks: undefine.yml
- name: Images
  ansible.builtin.include_tasks: images.yml
- name: Port Forward
  ansible.builtin.include_tasks: port_forward.yml
- name: Store Facts
  ansible.builtin.include_tasks: store_facts.yml
