---
- name: List all domain names
  ansible.builtin.command: virsh list --all --name
  changed_when: false
  register: libvirt_list_all_result

- name: Extract all domain names
  ansible.builtin.set_fact:
    libvirt_all_domains: "{{ libvirt_list_all_result.stdout_lines }}"

- name: Undefine machine
  ansible.builtin.command: 'virsh undefine "{{ item }}"'
  when: item in libvirt_all_domains
  changed_when: true
  loop: "{{ libvirt_domain_names }}"
