---
- name: Setup libvirt host delegate
  delegate_to: "{{ libvirt_hostname }}"
  block:
    - name: Ensure facts of the backup are available
      ansible.builtin.setup:
      delegate_facts: true

- name: Facts
  ansible.builtin.set_fact:
    libvirt_port_forward_hooks_folder: "{{ libvirt_host_qemu_machine_hooks_folder }}/{{ ansible_hostname }}"
    libvirt_port_forward_tmp_args: "{{ lookup('template', '../templates/port_forward_args.json.j2') }}"

- name: File names
  ansible.builtin.set_fact:
    libvirt_port_forward_managed_files: "{{ lookup('template', '../templates/file_names.j2') }}"

- name: Run on host
  delegate_to: "{{ libvirt_hostname }}"
  block:
    - name: Hooks folder
      ansible.builtin.file:
        dest: "{{ libvirt_port_forward_hooks_folder }}"
        state: directory
        mode: "755"

    - name: Hook scripts
      ansible.builtin.template:
        dest: "{{ libvirt_port_forward_hooks_folder }}/{{ libvirt_port_forward_hook_script_name }}"
        src: 'port_forward.sh.j2'
        mode: "700"
      loop: "{{ libvirt_port_forward_tmp_args }}"
      register: libvirt_port_forward_tmp_hook_scripts_result

    - name: List existing hook scripts
      ansible.builtin.shell: >
        find
        {{ libvirt_port_forward_hooks_folder }}
        -mindepth 1
        -name '{{ manage_name }}_*'
        -type f
        -printf '%P\n'
      changed_when: false
      register: libvirt_port_forward_tmp_existing_files

    - name: Stop unused hook scripts
      ansible.builtin.command: "{{ libvirt_port_forward_hooks_folder }}/{{ item }} stopped"
      changed_when: true
      failed_when: false
      when: item not in libvirt_port_forward_managed_files
      loop: "{{ libvirt_port_forward_tmp_existing_files.stdout_lines }}"

    - name: Remove unused hook scripts
      ansible.builtin.file:
        dest: "{{ libvirt_port_forward_hooks_folder }}/{{ item }}"
        state: absent
      when: item not in libvirt_port_forward_managed_files
      loop: "{{ libvirt_port_forward_tmp_existing_files.stdout_lines }}"

    - name: Start new hook scripts
      ansible.builtin.command: "{{ item.dest }} start"
      when: item.changed and true
      changed_when: true
      loop: "{{ libvirt_port_forward_tmp_hook_scripts_result.results }}"
