---
- name: Ensure image path exists
  ansible.builtin.file:
    path: "{{ libvirt_images_path }}"
    state: directory
    recurse: true

- name: Download sums and signature
  ansible.builtin.get_url:
    url: "{{ libvirt_images_ubuntu_cloud_url_base }}/{{ item }}"
    dest: "{{ libvirt_images_ubuntu_cloud_tmp_folder }}/{{ item }}"
    force: true
    mode: "644"
  changed_when: false
  loop:
    - "{{ libvirt_images_ubuntu_cloud_sha256sums }}"
    - "{{ libvirt_images_ubuntu_cloud_sha256sums_gpg }}"

- name: Check GPG keys
  ansible.builtin.command: >
    gpg
    --list-keys {{ libvirt_images_ubuntu_cloud_gpg_keys }}
  failed_when: false
  changed_when: false
  register: libvirt_images_ubuntu_cloud_gpg_result

- name: Import GPG key
  ansible.builtin.command: >
    gpg
    --keyserver {{ libvirt_images_ubuntu_cloud_gpg_key_server }}
    --recv-keys {{ libvirt_images_ubuntu_cloud_gpg_keys }}
  changed_when: true
  when: libvirt_images_ubuntu_cloud_gpg_result.rc != 0

- name: Check and extract signature
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      gpg
      --verify {{ libvirt_images_ubuntu_cloud_sha256sums_gpg }}
      {{ libvirt_images_ubuntu_cloud_sha256sums }}
      &&
      cat {{ libvirt_images_ubuntu_cloud_sha256sums }}
      | grep {{ libvirt_images_ubuntu_cloud_image_url | basename }}
      | cut -f 1 -d " "
    executable: /bin/bash
    chdir: "{{ libvirt_images_ubuntu_cloud_tmp_folder }}"
  changed_when: false
  register: libvirt_images_ubuntu_cloud_sha256_result

- name: Store sha256sum
  ansible.builtin.set_fact:
    libvirt_images_ubuntu_cloud_image_sha256: "{{ libvirt_images_ubuntu_cloud_sha256_result.stdout }}"

- name: Download image disk
  ansible.builtin.get_url:
    url: "{{ libvirt_images_ubuntu_cloud_image_url }}"
    checksum: "sha256:{{ libvirt_images_ubuntu_cloud_image_sha256 }}"
    dest: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_dist }}"
    mode: "644"
  register: libvirt_images_ubuntu_cloud_download_result

- name: Remove modified image
  ansible.builtin.file:
    path: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"
    state: absent
  when: libvirt_images_ubuntu_cloud_download_result.changed and true

- name: Convert the image
  ansible.builtin.command: "qemu-img convert -O qcow2 {{ libvirt_images_ubuntu_cloud_image_dist }} {{ libvirt_images_ubuntu_cloud_image_name }}"
  args:
    chdir: "{{ libvirt_images_path }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"

- name: Store Facts
  ansible.builtin.include_tasks: store_facts.yml
  when: libvirt_images_ubuntu_cloud_download_result.changed and true
