---
- name: store_facts | facts directory
  ansible.builtin.file:
    path: "{{ ansible_facts_path }}"
    state: directory
    recurse: yes

- name: "store_facts | ubuntu_{{ libvirt_images_ubuntu_cloud_image_name }}_cloud_image_path"
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "ubuntu_{{ libvirt_images_ubuntu_cloud_image_distribution }}_cloud_image_path"
    value: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"

- name: store_facts | re-read
  ansible.builtin.setup:
    filter: ansible_local
